### ISSUE TITLE
Update to support Laravel 5

### ISSUE THREAD

**Issue by ryantology** [capistrano/laravel#12]
The current structure is intended for Laravel 4.

This patch would solve part of the changes.
https://github.com/morrislaptop/laravel/commit/e310bc164a4955f4eb8213b51758d7bbad237b98

It's possible that there should be a separate branch for v4 vs v5?

**Comment by ikari7789** [comment]
Sorry for the late response. I'll be helping maintain this plugin for the foreseeable future. If any of these issues are still persisting (all of the tickets are quite old), please let me know and I will do what I can to try and help fix things.

This should be fixed with the latest version that I merged in. Please let me know.

**Comment by ikari7789** [comment]
If you're still having issues, please open a new issue.
