### ISSUE TITLE
Composer install takes a long time

### ISSUE THREAD

**Issue by martijn94** [capistrano/laravel#21]
Hi 

I'm having an issue with the following command:

composer install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader

00:08 composer:run
      01 composer install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader
      01 Generating optimized class loader
    ✔ 01 **@server.com 132.247s

The command takes up to 2 minutes, when I run the command directly on the server it only takes a few seconds. Is this a problem within the package or do you suspect something else to be in the way here?

**Comment by ikari7789** [comment]
This issue may be better to be asked on https://github.com/capistrano/composer. Unfortunately it seems like that project is also abandoned. I'll try to look into this this week and see if there's anything I could maybe do to speed it up, but it may just be due to how Capistrano interacts with the server (via SSH, etc.)
